libhugetlbfs: Fix contains reference to TMPDIR [buildpaths] error
ERROR: libhugetlbfs-1_2.24-r0 do_package_qa: QA Issue: File /usr/lib/libhugetlbfs/tests/obj64/dummy.ldscript in package libhugetlbfs-tests contains reference to TMPDIR [buildpaths]
ERROR: libhugetlbfs-1_2.24-r0 do_package_qa: Fatal QA errors were found, failing task.

Signed-off-by: alperak <alperyasinak1@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 1c346f1829e032c2c924b1aed3c5997ca91c7fa4)
Signed-off-by: Armin Kuster <akuster808@gmail.com>